### ISSUE TITLE
Improper handling of booleans as default values

### ISSUE THREAD

**Issue by jaalfaro** [hexlabsio/env-vars-ts#1]
You have a conflict when using a transform for booleans and default values.  In the requiredEnvs function, if you have a: 'true' in your environment, the default value is ignored and the transform runs resulting in a: true.  If you don't have the value in your env, and you use the default, a: true is then passed into the transfom, which is true === 'true', which will be false.  which is not what should happen.  Below is a test that should be added to validate.

    it('should allow setting of transformed type as default', () => {
      const environment = EnvironmentBuilder.create('a').optionals('c', 'd')
        .transform(s => s === 'true', 'a')
        .defaults({ a: true })
        .environment({ d: '123'});
      expect(environment).toEqual({a: true, d: '123'});
    });

**Comment by chrisbarbour** [comment]
Good catch! And thanks for the interest in the library, There is a PR going in shortly for this with your suggested test.

**Comment by chrisbarbour** [comment]
@jaalfaro You can find the updates in the latest version : @hexlabs/env-vars-ts@2.0.14
